# Generated by Django 4.2.7 on 2023-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_currencyrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrequest",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
