# Generated by Django 4.2.7 on 2023-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_currencyrequest_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrequest",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
